micronaut:
  application:
    name: oda-actions-service
  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  executors:
    publishers:
      type: fixed
      nThreads: 2
flyway:
  datasources:
    default:
      enabled: true
      schemas: 'actions'
      default-schema: 'actions'
datasources:
  default:
    schema: 'actions'
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
